### ISSUE TITLE
ModuleNotFoundError: No module named 'abnumber'

### ISSUE THREAD

**Issue by linuxonly801** [Graylab/IgFold#34]
when i follow the demo, the following error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/personal/yankai/LiuChang/IgFold/igfold/IgFoldRunner.py", line 120, in fold
    truncate_sequences=truncate_sequences,
  File "/data/personal/yankai/LiuChang/IgFold/igfold/utils/folding.py", line 220, in fold
    do_renum=do_renum,
  File "/data/personal/yankai/LiuChang/IgFold/igfold/utils/folding.py", line 134, in process_prediction
    from igfold.utils.abnumber_ import renumber_pdb
  File "/data/personal/yankai/LiuChang/IgFold/igfold/utils/abnumber_.py", line 2, in <module>
    from abnumber import Chain
ModuleNotFoundError: No module named 'abnumber'

so, where can I find the abnumber? I only found abnumber_.py.

**Comment by px172** [comment]
Try https://github.com/prihoda/AbNumber 

conda install -c bioconda abnumber

**Comment by jeffreyruffolo** [comment]
Sorry for the vague error, but yes the issue can be resolved by install abnumber. If you don't want to install / or not able, you can also pass `do_renum=False` to the function.
